import NavigationHeader from "@/components/navigation-header/navigation-header";

export const metadata = {
  title: "Hassan Imtiaz",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationHeader />
        {children}
      </body>
    </html>
  );
}
