import { ChakraProvider } from '@chakra-ui/react'
import classes from "../../styles/styles.module.css";
import NavigationHeader from "@/components/navigation-header/navigation-header";

export const metadata = {
  title: "Hassan Imtiaz",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classes.bodyContainer}>
        <ChakraProvider>
          <NavigationHeader />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
